"""
split3/hlf_gateway.py
---------------------
Hyperledger Fabric gateway for BATFL Module 2.

This implementation uses the Fabric peer CLI through WSL instead of a Python
gateway SDK. That keeps the project runnable on the current workspace where a
Python Fabric SDK package is not available.

Connection settings are read from split3/hlf/fabric_connection.env,
which is auto-generated by split3/hlf/setup.sh.

API is compatible with SimBlockchainGateway — governance.py needs zero changes.
"""
from __future__ import annotations
import json
import logging
import os
import shlex
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ── Locate fabric_connection.env ──────────────────────────────────────────────
def _find_env() -> Optional[Path]:
    this = Path(__file__).resolve()
    for p in [
        this.parent / "hlf" / "fabric_connection.env",
        this.parent.parent / "split3" / "hlf" / "fabric_connection.env",
    ]:
        if p.exists():
            return p
    return None

def _load_env(path: Path) -> Dict[str, str]:
    env = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            env[k.strip()] = v.strip()
    return env


def _to_wsl_path(path_text: str) -> str:
    """Convert a Windows path to a WSL path when possible."""
    normalized = path_text.replace("\\", "/")
    if len(normalized) >= 2 and normalized[1] == ":":
        drive = normalized[0].lower()
        rest = normalized[2:]
        if rest.startswith("/"):
            rest = rest[1:]
        return f"/mnt/{drive}/{rest}"
    return normalized


def _looks_like_windows_path(value: str) -> bool:
    return len(value) >= 2 and value[1] == ":"

# Fabric CLI is available when WSL exists and the network setup file can be found.
HLF_AVAILABLE = True


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
class HLFGateway:
    """
    Production Hyperledger Fabric gateway.
    Drop-in replacement for SimBlockchainGateway — identical method signatures.
    """

    def __init__(self, msp_id: str = "Org1MSP", env: Dict = None):
        if env is None:
            env_file = _find_env()
            if env_file is None:
                raise FileNotFoundError(
                    "fabric_connection.env not found.\n"
                    "Run: cd module1/split3/hlf && ./setup.sh")
            env = _load_env(env_file)

        self._msp_id   = msp_id
        self._channel  = env.get("FABRIC_CHANNEL",   "mychannel")
        self._chaincode= env.get("FABRIC_CHAINCODE",  "trust-registry")
        self._env      = env
        self._project_root = Path(__file__).resolve().parents[2]
        self._hlf_dir_wsl = _to_wsl_path(str(self._project_root / "module1" / "split3" / "hlf"))
        self._fabric_bin_wsl = _to_wsl_path(str(self._project_root / "fabric-samples" / "bin"))
        self._fabric_cfg_wsl = _to_wsl_path(str(self._project_root / "fabric-samples" / "config"))
        self._test_network_dir_wsl = _to_wsl_path(str(self._project_root / "fabric-samples" / "test-network"))
        self._orderer_ca = self._wsl_path(env["FABRIC_ORDERER_TLS_CERT"])
        self._peer1_tls = self._wsl_path(env["FABRIC_ORG1_TLS_CERT"])
        self._peer2_tls = self._wsl_path(env["FABRIC_ORG2_TLS_CERT"])
        self._peer1_addr = env.get("FABRIC_PEER_ORG1_ENDPOINT", "localhost:7051")
        self._peer2_addr = env.get("FABRIC_PEER_ORG2_ENDPOINT", "localhost:9051")

        is_org2   = (msp_id == env.get("FABRIC_ORG2_MSP_ID", "Org2MSP"))
        self._org2 = is_org2
        self._peer_address = self._peer2_addr if is_org2 else self._peer1_addr
        self._msp_id_env = env.get("FABRIC_ORG2_MSP_ID" if is_org2 else "FABRIC_ORG1_MSP_ID", msp_id)
        self._msp_config_path = self._wsl_path(env["FABRIC_ORG2_CERT" if is_org2 else "FABRIC_ORG1_CERT"]).rsplit("/signcerts/", 1)[0]

        self._peer_env = {
            "CORE_PEER_TLS_ENABLED": "true",
            "CORE_PEER_LOCALMSPID": self._msp_id_env,
            "CORE_PEER_MSPCONFIGPATH": self._wsl_path(env["FABRIC_ORG2_CERT" if is_org2 else "FABRIC_ORG1_CERT"]).rsplit("/signcerts/", 1)[0],
            "CORE_PEER_ADDRESS": self._peer_address,
            "CORE_PEER_TLS_ROOTCERT_FILE": self._peer2_tls if is_org2 else self._peer1_tls,
            "ORDERER_CA": self._orderer_ca,
        }
        logger.info(f"[HLFGateway] Connected via Fabric CLI: peer={self._peer_address} org={msp_id} ch={self._channel}")

    # ── Model Registry ────────────────────────────────────────────────────────
    def register_model(self, round_num, model_hash, block_hash, prev_block_hash,
                       global_f1=0.0, global_auc=0.0, trusted_clients=None,
                       flagged_clients=None, param_count=0, total_bytes=0):
        args = [
            str(round_num), model_hash, block_hash, prev_block_hash,
            str(round(global_f1, 6)), str(round(global_auc, 6)),
            json.dumps(trusted_clients or []), json.dumps(flagged_clients or []),
            str(param_count), str(total_bytes),
        ]
        tx_id, ok = self._submit("RegisterModel", args)
        if ok:
            record = self.get_model_record(round_num)
            ok = bool(record and int(record.get("round", -1)) == int(round_num))
        if ok:
            print(f"  [HLF] ✅ Round {round_num} on Fabric. tx={tx_id[:12]}...")
        else:
            print(f"  [HLF] ❌ Round {round_num} failed.")
        return tx_id, ok

    def verify_model_hash(self, round_num, claimed_hash):
        r = self._evaluate("VerifyModelHash", [str(round_num), claimed_hash])
        return json.loads(r) if r else {"verified": False}

    def get_model_record(self, round_num):
        r = self._evaluate("GetModel", [str(round_num)])
        return json.loads(r) if r else None

    def get_all_model_records(self):
        r = self._evaluate("QueryAllModels", [])
        parsed = json.loads(r) if r else []
        return parsed if isinstance(parsed, list) else []

    # ── Tamper Alerts ─────────────────────────────────────────────────────────
    def raise_tamper_alert(self, round_num, alert_type, detail, severity="HIGH"):
        tx_id, ok = self._submit("RaiseTamperAlert",
                                  [str(round_num), alert_type, detail, severity])
        return tx_id, {"alert_type": alert_type, "round": round_num, "tx_id": tx_id}

    def get_tamper_alerts(self):
        r = self._evaluate("GetAlerts", [])
        parsed = json.loads(r) if r else []
        return parsed if isinstance(parsed, list) else []

    # ── Audit Log ─────────────────────────────────────────────────────────────
    def append_audit_event(self, event_type, round_num, data, actor="FederatedCoordinator"):
        tx_id, _ = self._submit("AppendEvent",
                                 [event_type, str(round_num), actor, json.dumps(data)])
        return tx_id

    def get_audit_trail(self):
        r = self._evaluate("ExportAuditTrail", [])
        parsed = json.loads(r) if r else []
        return parsed if isinstance(parsed, list) else []

    # ── Ledger ────────────────────────────────────────────────────────────────
    def get_block_count(self):
        try:
            return len(self.get_all_model_records())
        except Exception:
            return -1

    def verify_ledger(self):
        try:
            records = self.get_all_model_records()
            if not records:
                return True, ["Ledger empty."]
            ok, msgs, prev = True, [], "GENESIS"
            for rec in sorted(records, key=lambda r: r.get("round", 0)):
                if rec.get("prevBlockHash") != prev:
                    ok = False
                    msgs.append(f"Chain break at round {rec.get('round')}")
                prev = rec.get("blockHash", "")
            if ok:
                msgs.append(f"Hash chain intact across {len(records)} rounds.")
            return ok, msgs
        except Exception as e:
            return False, [str(e)]

    def print_summary(self):
        records  = self.get_all_model_records()
        alerts   = self.get_tamper_alerts()
        audit    = self.get_audit_trail()
        ok, msgs = self.verify_ledger()
        print(f"\n  [HLFGateway] org={self._msp_id} channel={self._channel}")
        print(f"  FL Rounds: {len(records)}  Alerts: {len(alerts)}  Audit Events: {len(audit)}")
        for m in msgs:
            print(f"    {m}")

    def close(self):
        return None

    def __enter__(self): return self
    def __exit__(self, *_): self.close()

    # ── Internal ──────────────────────────────────────────────────────────────
    def _submit(self, fn: str, args: List[str]) -> Tuple[str, bool]:
        try:
            command = self._build_peer_command(
                ["chaincode", "invoke",
                 "-o", "localhost:7050",
                 "--ordererTLSHostnameOverride", "orderer.example.com",
                 "--tls",
                 "--cafile", self._orderer_ca,
                 "-C", self._channel,
                 "-n", self._chaincode,
                 "--peerAddresses", self._peer1_addr,
                 "--tlsRootCertFiles", self._peer1_tls,
                 "--peerAddresses", self._peer2_addr,
                 "--tlsRootCertFiles", self._peer2_tls,
                 "--waitForEvent",
                 "--waitForEventTimeout", "60s",
                 "-c", self._chaincode_payload(fn, args)],
            )
            result = subprocess.run(
                ["wsl", "bash", "-lc", command],
                capture_output=True,
                text=True,
            )
            output = (result.stdout or "") + (result.stderr or "")
            if result.returncode != 0:
                msg = (result.stderr or result.stdout or "").strip()
                logger.error(f"[HLF] Submit {fn} failed: {msg}")
                return f"error:{msg[:180]}", False
            tx_id = self._derive_tx_id(fn, args, output)
            return tx_id, result.returncode == 0
        except Exception as e:
            logger.error(f"[HLF] Submit {fn}: {e}")
            return f"error:{e}", False

    def _evaluate(self, fn: str, args: List[str]) -> Optional[str]:
        try:
            command = self._build_peer_command(
                ["chaincode", "query",
                 "-C", self._channel,
                 "-n", self._chaincode,
                 "-c", self._chaincode_payload(fn, args)],
            )
            result = subprocess.run(
                ["wsl", "bash", "-lc", command],
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                logger.error(f"[HLF] Evaluate {fn}: {result.stderr.strip() or result.stdout.strip()}")
                return None
            return (result.stdout or "").strip() or None
        except Exception as e:
            logger.error(f"[HLF] Evaluate {fn}: {e}")
            return None

    def _build_peer_command(self, peer_args: List[str]) -> str:
        safe_path = f"{self._fabric_bin_wsl}:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        exports = [f"export PATH={shlex.quote(safe_path)}"]
        exports.append(f"export FABRIC_CFG_PATH={shlex.quote(self._fabric_cfg_wsl)}")
        for key, value in self._peer_env.items():
            exports.append(f"export {key}={shlex.quote(value)}")
        exports.append(f"cd {shlex.quote(self._test_network_dir_wsl)}")
        exports.append("peer " + " ".join(shlex.quote(part) for part in peer_args))
        return " && ".join(exports)

    @staticmethod
    def _chaincode_payload(fn: str, args: List[str]) -> str:
        payload = {"function": fn, "Args": args}
        return json.dumps(payload, separators=(",", ":"))

    @staticmethod
    def _derive_tx_id(fn: str, args: List[str], output: str) -> str:
        import hashlib
        raw = json.dumps({"fn": fn, "args": args, "output": output}, sort_keys=True)
        return hashlib.sha256(raw.encode()).hexdigest()[:32]

    @staticmethod
    def _wsl_path(path_text: str) -> str:
        return _to_wsl_path(path_text) if _looks_like_windows_path(path_text) else path_text

    @staticmethod
    def _find_key(key_dir: str) -> str:
        p = Path(key_dir)
        if not p.is_dir():
            raise FileNotFoundError(
                f"Keystore directory not found: {key_dir}\n"
                "Run: cd module1/split3/hlf && ./setup.sh")
        for f in p.iterdir():
            if f.name.endswith("_sk") or f.suffix == ".pem":
                return str(f)
        files = list(p.iterdir())
        if files:
            return str(files[0])
        raise FileNotFoundError(f"No private key found in {key_dir}")
